# Generated by Django 4.2.1 on 2023-12-08 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarydetail',
            name='credited',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
